version: 2.1

commands:
  install:
    parameters:
      node-version:
        default: '14'
        type: string
    steps:
      - run:
          name: Set auth token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Verify cache settings
          command: |
            ls modules > /tmp/folders
            cat /tmp/folders | xargs node scripts/verify-paths.js
      - store-node-version
      - restore_cache:
          name: 'Restoring cache'
          key: yafu-node-{{ checksum "/tmp/node-version" }}-{{ checksum "yarn.lock" }}-{{ checksum "/tmp/folders" }}
      - run:
          name: 'Install packages'
          command: yarn install --frozen-lockfile
      - save_cache:
          name: 'Saving cache'
          key: yafu-node-{{ checksum "/tmp/node-version" }}-{{ checksum "yarn.lock" }}-{{ checksum "/tmp/folders" }}
          paths:
            #pathsbegin
            - node_modules
            - modules/const/node_modules
            - modules/create-rollup-config/node_modules
            - modules/curry/node_modules
            - modules/either/node_modules
            - modules/eslint-config-yafu/node_modules
            - modules/fantasy-functions/node_modules
            - modules/fantasy-types/node_modules
            - modules/identity/node_modules
            - modules/lens/node_modules
            - modules/maybe/node_modules
            - modules/rollup-plugin-curry/node_modules
            - modules/sort-dependencies/node_modules
            - modules/test-all-exports/node_modules
            - modules/transduce/node_modules
            - modules/type-utils/node_modules
            - modules/yafu/node_modules
            #pathsend
  run-tests:
    steps:
      - run:
          command: yarn test
          name: Run tests
      - store_test_results:
          path: test-results
  verify-exports:
    steps:
      - run:
          command: cd modules/test-all-exports && yarn verify
          name: Verify exports
  store-node-version:
    steps:
      - run:
          name: Store node version
          command: |
            node -v | tee /tmp/node-version
  commitlint:
    steps:
      - run:
          command: npx commitlint --from origin/master
          name: Commitlint
  sort-package-json:
    steps:
      - run:
          command: |
            yarn lerna exec "npx sort-package-json --check"
            npx sort-package-json
          name: Verify package jsons sorted
jobs:
  test:
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>
    steps:
      - checkout
      - install:
          node-version: << parameters.node-version >>
      - run-tests
      - verify-exports
  checks:
    resource_class: small
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - install:
          node-version: '14'
      - commitlint
      - sort-package-json

workflows:
  test-all:
    jobs:
      - checks
      - test:
          matrix:
            parameters:
              node-version: [ '14.19', '16.15' ]
